import type {
  AdminEventFilterParams,
  AuditLogFilterParams,
  AdminReviewFilterParams,
  AdminTournamentFilterParams,
  AdminUserFilterParams,
  AdminVenueFilterParams,
  EventFilterParams,
  MyEventsParams,
  MyPartnerRequestsParams,
  MyReportsFilterParams,
  MyTournamentsParams,
  PartnerRequestFilterParams,
  ProfileFilterParams,
  RatingSyncLogFilterParams,
  ReportQueueFilterParams,
  ReviewFilterParams,
  TournamentFilterParams,
  VenueFilterParams,
} from "@/types/api";
import type { ParticipantStatus } from "@/lib/enums";

export const qk = {
  me: ["me"] as const,
  sessions: ["sessions"] as const,
  events: (filter?: EventFilterParams) => ["events", filter ?? {}] as const,
  event: (id: number) => ["event", id] as const,
  eventParticipants: (id: number, status?: ParticipantStatus) =>
    ["event", id, "participants", status ?? "all"] as const,
  myEvents: (params?: MyEventsParams) => ["myEvents", params ?? {}] as const,
  partnerRequests: (filter?: PartnerRequestFilterParams) => ["partnerRequests", filter ?? {}] as const,
  partnerRequest: (id: number) => ["partnerRequest", id] as const,
  partnerResponses: (id: number) => ["partnerRequest", id, "responses"] as const,
  myPartnerRequests: (params?: MyPartnerRequestsParams) => ["myPartnerRequests", params ?? {}] as const,
  notifications: ["notifications"] as const,
  unreadCount: ["notifications", "unread"] as const,
  profiles: (filter?: ProfileFilterParams) => ["profiles", filter ?? {}] as const,
  profile: (slug: string) => ["profile", slug] as const,
  ratingHistory: (slug: string) => ["profile", slug, "rating-history"] as const,
  myProfile: ["myProfile"] as const,
  myRatingHistory: ["myProfile", "rating-history"] as const,
  venues: (filter?: VenueFilterParams) => ["venues", filter ?? {}] as const,
  venue: (slug: string) => ["venue", slug] as const,
  venueLayouts: (venueId: number) => ["venueLayout", venueId] as const,
  venueLayout: (venueId: number, date: string) => ["venueLayout", venueId, date] as const,
  reviews: (filter?: ReviewFilterParams) => ["reviews", filter ?? {}] as const,
  tournaments: (filter?: TournamentFilterParams) => ["tournaments", filter ?? {}] as const,
  tournament: (slug: string) => ["tournament", slug] as const,
  tournamentParticipants: (id: number, status?: ParticipantStatus) =>
    ["tournament", id, "participants", status ?? "all"] as const,
  myTournaments: (params?: MyTournamentsParams) => ["myTournaments", params ?? {}] as const,
  reportQueue: (filter?: ReportQueueFilterParams) => ["reportQueue", filter ?? {}] as const,
  report: (id: number) => ["report", id] as const,
  myReports: (filter?: MyReportsFilterParams) => ["myReports", filter ?? {}] as const,
  adminUsers: (filter?: AdminUserFilterParams) => ["adminUsers", filter ?? {}] as const,
  adminUser: (id: number) => ["adminUser", id] as const,
  adminVenues: (filter?: AdminVenueFilterParams) => ["adminVenues", filter ?? {}] as const,
  adminEvents: (filter?: AdminEventFilterParams) => ["adminEvents", filter ?? {}] as const,
  adminTournaments: (filter?: AdminTournamentFilterParams) =>
    ["adminTournaments", filter ?? {}] as const,
  adminReviews: (filter?: AdminReviewFilterParams) => ["adminReviews", filter ?? {}] as const,
  ratingSyncLog: (filter?: RatingSyncLogFilterParams) => ["ratingSyncLog", filter ?? {}] as const,
  ratingSyncStale: (params?: { limit?: number; offset?: number }) =>
    ["ratingSyncStale", params ?? {}] as const,
  auditLog: (filter?: AuditLogFilterParams) => ["auditLog", filter ?? {}] as const,
  venueStaff: (venueId: number) => ["venueStaff", venueId] as const,
  managedVenues: () => ["managedVenues"] as const,
  venueBookings: (venueId: number) => ["venueBookings", venueId] as const,
  venueModEvents: (venueId: number) => ["venueModEvents", venueId] as const,
  venueModReviews: (venueId: number) => ["venueModReviews", venueId] as const,
};
